service: highscorebackend
configValidationMode: error  
custom: 
  webpack: 
    webpackConfig: ./webpack.config.js
    includeModules: true

# you can add packaging information here
# package:
#  include:
#    - lib
#    - node_modules
#  exclude:
#    - package.json
#  artifact: my-service-code.zip
  

provider:
  name: aws
  profile: serverlessUser
  runtime: nodejs12.x
  stage: prod
  region: eu-west-1
  memorySize: 128
  timeout: 30

plugins:
 - serverless-webpack 
 - serverless-offline
 - serverless-dynamodb-local


functions:
  hello:
    handler: handler.hello
    events:
      - http: 
          path: hello
          method: get

#   you can add any of the following events
#   events:
#     - http:
#         path: users/create
#         method: get
#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
resources:
  Resources:
    highscore:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: highscore
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH      
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
